apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kmmr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kmmr
    app.kubernetes.io/part-of: byoc-app-hiih
  name: kmmr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: kmmr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: kmmr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-zdvi-tenant/byoc-app-hiih/kmmr@sha256:c1709fec99bb12042282336feb6e2cada2efd58f86e990e59258bad6a44d29be
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
